### Register User
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "Nderitu",
  "email":  "Nderitu@mail.com",
  "password": "password",
  "role":  "ADMIN"
},